### ISSUE TITLE
Redo Blog subscription process

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/codeinwp-blog#11]
Quoting @ineagu here:

> 1. For the goodie, a developer should configure sendinblue, so when a user subscribes to those forms, they will be added to (xxx) list ( a list you can create already and provide the ID ).

> 2.On sendinblue automation we can configure a scenario, when a user is added to xxx list, he will get a particular email.

> We should work on development branch and test it out before. btw the staging site is : http://staging-codeinwpblog.kinsta.com

**Comment by s2abina** [comment]
@selul can you help with a new subscription process for CodeinWP Blog so that the users receive an email with a link to the resource they're subscribing for?

**Comment by selul** [comment]
@ineagu @s2abina  i dont understand what a goodie is, in this context, and neither have too much experience in sendblue automation, i think either you or ionut can build the workflow in SIB to be more time efficient.
