### ISSUE TITLE
add https://ro.wordpress.org/plugins/header-footer/

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/codeinwp-blog#12]
@selul https://ro.wordpress.org/plugins/header-footer/

**Comment by ineagu** [comment]
-- Please reply above this line --


Hi, thank you for contacting ThemeIsle—this is a friendly automated
reply.

Your request has been received and it is currently being reviewed, and
a real, human Support Engineer will get back to you by the end of the
next business day (excluding weekends).

See you soon!
Friends at ThemeIsle

**Comment by selul** [comment]
@ineagu cred ca ai vreun workflow pe email.

**Comment by ineagu** [comment]
-- Please reply above this line --


Hi, thank you for contacting ThemeIsle—this is a friendly automated
reply.

Your request has been received and it is currently being reviewed, and
a real, human Support Engineer will get back to you by the end of the
next business day (excluding weekends).

See you soon!
Friends at ThemeIsle

**Comment by ineagu** [comment]
-- Please reply above this line --


Hi, thank you for contacting ThemeIsle—this is a friendly automated
reply.

Your request has been received and it is currently being reviewed, and
a real, human Support Engineer will get back to you by the end of the
next business day (excluding weekends).

See you soon!
Friends at ThemeIsle

**Comment by ineagu** [comment]
-- Please reply above this line --


Hi, thank you for contacting ThemeIsle—this is a friendly automated
reply.

Your request has been received and it is currently being reviewed, and
a real, human Support Engineer will get back to you by the end of the
next business day (excluding weekends).

See you soon!
Friends at ThemeIsle
