### ISSUE TITLE
UX testing - analyse how users navigate / use theme listings.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/codeinwp-blog#21]
This is about articles like this: https://www.codeinwp.com/blog/education-wordpress-themes/

You can find insights on hotjar. You can work on this with @dascalescuro.

cc: @ineagu

**Comment by abaicus** [comment]
The goal here would be to find out how we can visually improve the listings to get more engagement based on the behaviors we already know about.

**Comment by dascalescuro** [comment]
Cred ca primul pas ar fi sa listam articolele pentru care vrem sa facem analiza.
Ulterior le prioritizam si dupa ce testam / analizam sa tragem niste concluzii pe care sa le sharuim.

Cred ca Adelina ne poate ajuta cu o lista a articolelor unde avem listinguri?
@abaicus ce parere ai, vorbesc cu Adelina sa ne ajute cu o lista sau putem incepe direct cu articolul indicat mai sus?

**Comment by abaicus** [comment]
Cred ca avem deja niste date pentru listingul de free WordPress themes de aici: 
https://www.codeinwp.com/blog/best-free-wordpress-themes/
https://insights.hotjar.com/sites/379722/heatmap/report/1040779?device=desktop&type=click

Cred ca nu are neaparat relevatna cand au fost stranse pentru ca listingurile inca arata la fel. Ar trebui sa optimizam cumva procesul de parcurgere al paginii. Ce parere aveti? @mihneastanciu @dascalescuro

**Comment by dascalescuro** [comment]
@abaicus ai dreptate, nu cred ca are relevanta cand au fost stranse datele.

putem strange niste idei (gen brainstorming) -> unele am putea sa le validam intre noi si sa le implementam altele putem testa cu GO.

cred ca ar fi OK sa ne vedem pentru 30-45 minute sa stabilim ce idei avem si care ar fi pasii urmatori.
