### ISSUE TITLE
review lighthouse + reported issues

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/codeinwp-blog#54]
@cosmin-serbanescu in case when I missed adding some reported stuff here, please don't forget to list them yourself so you can plan and don't miss them + tie them to code commits, I have some a bit old notes here in case it helps to break them in separate issues : 

design new optin forms + replace optinmonster
remove DCL, loading comments number from WP
wp-deque unused styles
maybe replace footer/header elementor
3 times load GA
why load google fonts?
lazy-load load jumping effect
menu should still work/dropdown show without js

Current menu color is diffeernt than before, it used to be blue.
Footer seems out of place : https://www.dropbox.com/s/6yij8m5yxvwkz0u/Screenshot%202018-11-05%2017.35.12.png?dl=0
This would ideally be on 1 line : https://www.dropbox.com/s/r53yj5i35nv2ee2/Screenshot%202018-11-05%2017.35.34.png?dl=0
All sub-menu items should be on 1-line, it used to be like this : https://www.dropbox.com/s/pe24favt4sxoat3/Screenshot%202018-11-05%2017.35.50.png?dl=0
I have a really hard time closing the search overlay in safari, probably due to some js that keeps running in loop

**Comment by cosmin-serbanescu** [comment]
moved to https://github.com/Codeinwp/codeinwp/issues/61
